// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: hosts_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetHostnameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
}

func (x *SetHostnameRequest) Reset() {
	*x = SetHostnameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hosts_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetHostnameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHostnameRequest) ProtoMessage() {}

func (x *SetHostnameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hosts_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHostnameRequest.ProtoReflect.Descriptor instead.
func (*SetHostnameRequest) Descriptor() ([]byte, []int) {
	return file_hosts_service_proto_rawDescGZIP(), []int{0}
}

func (x *SetHostnameRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type SetHostnameResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SetHostnameResponce) Reset() {
	*x = SetHostnameResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hosts_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetHostnameResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHostnameResponce) ProtoMessage() {}

func (x *SetHostnameResponce) ProtoReflect() protoreflect.Message {
	mi := &file_hosts_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHostnameResponce.ProtoReflect.Descriptor instead.
func (*SetHostnameResponce) Descriptor() ([]byte, []int) {
	return file_hosts_service_proto_rawDescGZIP(), []int{1}
}

func (x *SetHostnameResponce) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListDNSServersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListDNSServersRequest) Reset() {
	*x = ListDNSServersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hosts_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDNSServersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDNSServersRequest) ProtoMessage() {}

func (x *ListDNSServersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hosts_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDNSServersRequest.ProtoReflect.Descriptor instead.
func (*ListDNSServersRequest) Descriptor() ([]byte, []int) {
	return file_hosts_service_proto_rawDescGZIP(), []int{2}
}

type ListDNSServersResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Servers []string `protobuf:"bytes,1,rep,name=servers,proto3" json:"servers,omitempty"`
}

func (x *ListDNSServersResponce) Reset() {
	*x = ListDNSServersResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hosts_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListDNSServersResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDNSServersResponce) ProtoMessage() {}

func (x *ListDNSServersResponce) ProtoReflect() protoreflect.Message {
	mi := &file_hosts_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDNSServersResponce.ProtoReflect.Descriptor instead.
func (*ListDNSServersResponce) Descriptor() ([]byte, []int) {
	return file_hosts_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListDNSServersResponce) GetServers() []string {
	if x != nil {
		return x.Servers
	}
	return nil
}

type AddDNSServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *AddDNSServerRequest) Reset() {
	*x = AddDNSServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hosts_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDNSServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDNSServerRequest) ProtoMessage() {}

func (x *AddDNSServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hosts_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDNSServerRequest.ProtoReflect.Descriptor instead.
func (*AddDNSServerRequest) Descriptor() ([]byte, []int) {
	return file_hosts_service_proto_rawDescGZIP(), []int{4}
}

func (x *AddDNSServerRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type AddDNSServerResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddDNSServerResponce) Reset() {
	*x = AddDNSServerResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hosts_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddDNSServerResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddDNSServerResponce) ProtoMessage() {}

func (x *AddDNSServerResponce) ProtoReflect() protoreflect.Message {
	mi := &file_hosts_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddDNSServerResponce.ProtoReflect.Descriptor instead.
func (*AddDNSServerResponce) Descriptor() ([]byte, []int) {
	return file_hosts_service_proto_rawDescGZIP(), []int{5}
}

func (x *AddDNSServerResponce) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveDNSServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
}

func (x *RemoveDNSServerRequest) Reset() {
	*x = RemoveDNSServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hosts_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveDNSServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDNSServerRequest) ProtoMessage() {}

func (x *RemoveDNSServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hosts_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDNSServerRequest.ProtoReflect.Descriptor instead.
func (*RemoveDNSServerRequest) Descriptor() ([]byte, []int) {
	return file_hosts_service_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveDNSServerRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

type RemoveDNSServerResponce struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RemoveDNSServerResponce) Reset() {
	*x = RemoveDNSServerResponce{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hosts_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveDNSServerResponce) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDNSServerResponce) ProtoMessage() {}

func (x *RemoveDNSServerResponce) ProtoReflect() protoreflect.Message {
	mi := &file_hosts_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDNSServerResponce.ProtoReflect.Descriptor instead.
func (*RemoveDNSServerResponce) Descriptor() ([]byte, []int) {
	return file_hosts_service_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveDNSServerResponce) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hosts_service_proto protoreflect.FileDescriptor

var file_hosts_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x68, 0x6f, 0x73, 0x74, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x72, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x12, 0x53,
	0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x2f, 0x0a,
	0x13, 0x53, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x17,
	0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x44,
	0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x22, 0x2d, 0x0a, 0x13, 0x41,
	0x64, 0x64, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x30, 0x0a, 0x14, 0x41, 0x64,
	0x64, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x30, 0x0a, 0x16,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0x33,
	0x0a, 0x17, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x32, 0xb9, 0x02, 0x0a, 0x0f, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x42, 0x0a, 0x0b, 0x53, 0x65, 0x74, 0x48, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x74, 0x6f, 0x2e, 0x53, 0x65,
	0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x70, 0x72, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x74, 0x48, 0x6f, 0x73, 0x74, 0x6e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0e, 0x4c,
	0x69, 0x73, 0x74, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73, 0x12, 0x1b, 0x2e,
	0x70, 0x72, 0x74, 0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70, 0x72, 0x74,
	0x6f, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x44,
	0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x74, 0x6f, 0x2e,
	0x41, 0x64, 0x64, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x74, 0x6f, 0x2e, 0x41, 0x64, 0x64, 0x44, 0x4e,
	0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x4e, 0x0a, 0x0f, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x44, 0x4e, 0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x44, 0x4e,
	0x53, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x63, 0x65, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hosts_service_proto_rawDescOnce sync.Once
	file_hosts_service_proto_rawDescData = file_hosts_service_proto_rawDesc
)

func file_hosts_service_proto_rawDescGZIP() []byte {
	file_hosts_service_proto_rawDescOnce.Do(func() {
		file_hosts_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_hosts_service_proto_rawDescData)
	})
	return file_hosts_service_proto_rawDescData
}

var file_hosts_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hosts_service_proto_goTypes = []any{
	(*SetHostnameRequest)(nil),      // 0: prto.SetHostnameRequest
	(*SetHostnameResponce)(nil),     // 1: prto.SetHostnameResponce
	(*ListDNSServersRequest)(nil),   // 2: prto.ListDNSServersRequest
	(*ListDNSServersResponce)(nil),  // 3: prto.ListDNSServersResponce
	(*AddDNSServerRequest)(nil),     // 4: prto.AddDNSServerRequest
	(*AddDNSServerResponce)(nil),    // 5: prto.AddDNSServerResponce
	(*RemoveDNSServerRequest)(nil),  // 6: prto.RemoveDNSServerRequest
	(*RemoveDNSServerResponce)(nil), // 7: prto.RemoveDNSServerResponce
}
var file_hosts_service_proto_depIdxs = []int32{
	0, // 0: prto.HostnameService.SetHostname:input_type -> prto.SetHostnameRequest
	2, // 1: prto.HostnameService.ListDNSServers:input_type -> prto.ListDNSServersRequest
	4, // 2: prto.HostnameService.AddDNSServer:input_type -> prto.AddDNSServerRequest
	6, // 3: prto.HostnameService.RemoveDNSServer:input_type -> prto.RemoveDNSServerRequest
	1, // 4: prto.HostnameService.SetHostname:output_type -> prto.SetHostnameResponce
	3, // 5: prto.HostnameService.ListDNSServers:output_type -> prto.ListDNSServersResponce
	5, // 6: prto.HostnameService.AddDNSServer:output_type -> prto.AddDNSServerResponce
	7, // 7: prto.HostnameService.RemoveDNSServer:output_type -> prto.RemoveDNSServerResponce
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hosts_service_proto_init() }
func file_hosts_service_proto_init() {
	if File_hosts_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hosts_service_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SetHostnameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hosts_service_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*SetHostnameResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hosts_service_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ListDNSServersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hosts_service_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ListDNSServersResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hosts_service_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*AddDNSServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hosts_service_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*AddDNSServerResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hosts_service_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveDNSServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hosts_service_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*RemoveDNSServerResponce); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hosts_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hosts_service_proto_goTypes,
		DependencyIndexes: file_hosts_service_proto_depIdxs,
		MessageInfos:      file_hosts_service_proto_msgTypes,
	}.Build()
	File_hosts_service_proto = out.File
	file_hosts_service_proto_rawDesc = nil
	file_hosts_service_proto_goTypes = nil
	file_hosts_service_proto_depIdxs = nil
}
